workflows:
  flutter-workflow:
    name: Flutter CI/CD
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play    # Define in Codemagic UI (signing & API keys)
        - app_store      # Define in Codemagic UI

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Run tests
        script: |
          flutter test

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build Android AAB
        script: |
          flutter build appbundle --release

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa

